version: '3.7'

services:
    webui:
        build:
            context: ./webui
        ports:
            - 4200:4200
        environment:
            - PROXY_PORT=8080
            - PROXY_HOST=server
        container_name: webui
        depends_on:
          - server
        links:
          - server
    server:
        build:
            context: ./server
        ports:
            - 4201:8080
        environment:
            - DATABASE_URL=mongodb://database:27017/myapp
        depends_on:
            - database
    database:
        image: mongo
        container_name: 'mongo_db'
        ports:
            - 27018:27017
